---
title: "ANA515 SU22 Assignment 1"
author: "Andrew Cutchin"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme:
     bootswatch: Superhero
---

```{r setup, include = FALSE}
install.packages("cli")
install.packages("dbplyr")
install.packages("tidyverse")
install.packages("knitr")
install.packages("bslib")
```

```{r setup, include = FALSE}
library(tidyverse)
library(knitr)
library(bslib)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include = FALSE}
url <- "https://raw.githubusercontent.com/fivethirtyeight/guns-data/master/full_data.csv"
gun_deaths <- read_csv(url)
glimpse(gun_deaths)
```

```{r setup, include=FALSE}
youth <- filter(gun_deaths, age<=65)
```

```{r setup, include=FALSE}
str(youth)
summary(youth)
dim(youth)
```

We have data about `r nrow(gun_deaths)` individuals killed by guns. Only `r nrow(gun_deaths) - r nrow(youth)` are older than 65. The distribution of the remainder is shown below: 

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
```

# Gun deaths by age
```{r youth-dist, echo=FALSE}
youth %>%
  ggplot(aes(age))+
  geom_freqpoly(binwidth=1)
```

# Gun deaths by race
```{r race_dist, echo=FALSE}
youth %>%
ggplot(aes(fct_infreq(race) %>% fct_rev())) +
geom_bar()+coord_flip()+
labs(x="Victim race")
```

